FROM alpine:latest

# Get development tools to build binaries
RUN apk add --update build-base

# Install mecab
RUN cd /tmp && \
    wget 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE' -O mecab-0.996.tar.gz && \
    tar -xvf mecab-0.996.tar.gz && \
    cd mecab-0.996/ && \
    ./configure  --with-charset=utf8 --enable-utf8-only --build=aarch64-unknown-linux-gnu && \
    make && \
    make install


# Install mecab ipadic dictionary
RUN cd /tmp && \
    wget 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM' -O mecab-ipadic-2.7.0-20070801.tar.gz && \
    tar zxvf mecab-ipadic-2.7.0-20070801.tar.gz && \
    cd mecab-ipadic-2.7.0-20070801 && \
    ./configure  --with-charset=utf8 && \
    make && \
    make install

# Add mozc dictionary to work with mecab
RUN cd /tmp && \
    apk add git python3 && \
    git clone --depth 1 https://github.com/aankittcoolest/mecab-as-kkc.git && \
    cd mecab-as-kkc/ && \
    make && \
    make install

# Empty tmp folder
RUN rm -rf /tmp/*