FROM aankittcoolest/mecab-mozc:1.0

COPY --from=golang:1.21-alpine /usr/local/go/ /usr/local/go/

ENV PATH="/usr/local/go/bin:${PATH}"

RUN mkdir -p /usr/src/app && cd /usr/src/app
WORKDIR /usr/src/app
COPY ./src/go.mod .
COPY ./src/go.sum .
RUN go mod download
COPY ./src/ .

CMD ["sh", "-c", "tail -f /dev/null"]